/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import management.system.model.RegModel;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import static management.system.ManagementSys.logger;
import management.system.Report;


import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import static net.sf.dynamicreports.report.builder.DynamicReports.report;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.constant.HorizontalAlignment;
import net.sf.dynamicreports.report.exception.DRException;

import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import static net.sf.dynamicreports.report.builder.DynamicReports.report;
import net.sf.dynamicreports.report.builder.ReportBuilder;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.constant.HorizontalAlignment;
import net.sf.dynamicreports.report.exception.DRException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignBand;
import net.sf.jasperreports.engine.design.JRDesignExpression;
import net.sf.jasperreports.engine.design.JRDesignField;
import net.sf.jasperreports.engine.design.JRDesignParameter;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JRDesignSection;
import net.sf.jasperreports.engine.design.JRDesignStaticText;
import net.sf.jasperreports.engine.design.JRDesignStyle;
import net.sf.jasperreports.engine.design.JRDesignTextField;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.type.HorizontalTextAlignEnum;

/**
 *
 * @Md.Dedarul Hasan
 */
public class EditRegUser extends javax.swing.JFrame {
static final Logger logger = Logger.getLogger(EditRegUser.class.getName());
    /**
     * Creates new form SearchRegUser
     */
    Connection con;
    Statement s;
    ResultSet rs;
    PreparedStatement ps;
    
    public EditRegUser() {
        con=Database.getConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userId = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        clearRegBtn = new javax.swing.JButton();
        backToSignupBtn = new javax.swing.JButton();
        printUserRegBtn = new javax.swing.JButton();
        prntDynBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Users Registration Informaitons");
        setLocation(new java.awt.Point(485, 185));
        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("User ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Father Name:");

        jLabel4.setText("Address:");

        userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdActionPerformed(evt);
            }
        });
        userId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userIdKeyReleased(evt);
            }
        });

        jLabel5.setText("Phone:");

        jLabel6.setText("E-mail:");

        jLabel7.setText("User Name:");

        jLabel8.setText("Password:");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Please Enter User ID First To Search & Update User Informations Here");

        clearRegBtn.setText("Clear");
        clearRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRegBtnActionPerformed(evt);
            }
        });

        backToSignupBtn.setText("Back To SignUp");
        backToSignupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToSignupBtnActionPerformed(evt);
            }
        });

        printUserRegBtn.setText("Print");
        printUserRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printUserRegBtnActionPerformed(evt);
            }
        });

        prntDynBtn.setText("PrintDynamic");
        prntDynBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prntDynBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addComponent(fName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(userId, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(backToSignupBtn))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(printUserRegBtn)
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(prntDynBtn)
                                        .addComponent(deleteBtn))))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(clearRegBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(exitBtn))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(email)
                                    .addComponent(userName)
                                    .addComponent(pass))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(exitBtn)
                    .addComponent(clearRegBtn)
                    .addComponent(backToSignupBtn))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printUserRegBtn)
                    .addComponent(prntDynBtn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();   
    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearRegBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearRegBtnActionPerformed

    private void backToSignupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToSignupBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Want to back Order Informations, Thanks..!!");
        Registation reg=new Registation();
        reg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_backToSignupBtnActionPerformed

    private void userIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userIdKeyReleased
        // TODO add your handling code here:
        try {
            String sql="select reg_id,name,fname,address,phone,mail,uname,pass from registation where reg_id=?";
            ps=con.prepareStatement(sql);
            ps.setString(1, userId.getText());
            rs=ps.executeQuery();
            if(rs.next()){
                String usersName=rs.getString("name");
                name.setText(usersName);
                String fatherName=rs.getString("fname");
                fName.setText(fatherName);
                String userAddress=rs.getString("address");
                address.setText(userAddress);
                String userPhone=rs.getString("phone");
                phone.setText(userPhone);
                String userMail=rs.getString("mail");
                email.setText(userMail);
                String uName=rs.getString("uname");
                userName.setText(uName);
                String userPass=rs.getString("pass");
                pass.setText(userPass);
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_userIdKeyReleased

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Database Updated");
        try {
            
            String sql="update registation set name=?,fname=?,address=?,phone=?,mail=?,uname=?,pass=? where reg_id=?";
            ps=con.prepareStatement(sql);
            
            ps.setString(1, name.getText());
            ps.setString(2, fName.getText());
            ps.setString(3, address.getText());
            ps.setString(4, phone.getText());
            ps.setString(5, email.getText());
            ps.setString(6, userName.getText());
            ps.setString(7, pass.getText());
            ps.setString(8, userId.getText());            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "User Information Updated Successfully");
            System.out.println("Database Updated");
            //*******************************************************
                logger.log(Level.SEVERE, "Login Successfull");
                logger.info("This is info message");
                logger.config("inventory system");
                logger.warning("Login Button Fired");
                System.out.println("Logic executed successfully....");
                //*******************************************************
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error,User Information Not Updated..!");
            System.out.println("Database not Updated");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Database Updated");
        try {
            
            String sql="delete from registation where reg_id=?;";
            ps=con.prepareStatement(sql);
            
            ps.setString(1, userId.getText());          
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "User Information Row Deleted Successfully");
            System.out.println("Database Updated");
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error,User Information Not Updated..!");
            System.out.println("Database not Updated");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void printUserRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printUserRegBtnActionPerformed
        // TODO add your handling code here:
        //createReportToPrint();
        Connection connection = null;
        Statement statement = null;
		try {
//			Class.forName("com.mysql.jdbc.Driver");
//                        connection = DriverManager.getConnection("jdbc:mysql://hostname:3306/inventorysystem","root", "root");
			connection = Database.getConnection();
                        statement = connection.createStatement();
                        HashMap parameterMap = new HashMap();
                        parameterMap.put("rtitle", "Report Title Here");//sending the report title as a parameter.
                        Report rpt = new Report(parameterMap, connection);
                        rpt.setReportName("report1"); //reportRegistration is the name of my jasper file.
                        rpt.callReport();
                        JOptionPane.showMessageDialog(rootPane, "DataBase Connected..!");
                        System.out.println("Database Connection Successfull");
                        
                        
//                        JasperReportBuilder report = DynamicReports.report();//a new report
//                        //JasperReprotBuilder jrb=new JasperReportBuilder();
//                       // JasperReportBuilder jsp=new JasperReportBuilder();
//                        //jsp.addColumn(columns);
//		report
//		  .columns(
//		  	Columns.column("Reg. Id", "reg_id", DataTypes.integerType()),
//		  		//.setHorizontalAlignment(HorizontalAlignment.LEFT),
//		  	Columns.column("User Name", "name", DataTypes.stringType()),
//		  	Columns.column("Father Name", "fname", DataTypes.stringType()),
//		  	Columns.column("User Address", "address", DataTypes.stringType()),
//		  		//.setHorizontalAlignment(HorizontalAlignment.LEFT),
//                        Columns.column("User Phone", "phone", DataTypes.stringType()),
//		  	Columns.column("User Mail", "mail", DataTypes.stringType()),
//                        Columns.column("User Name Login", "uname", DataTypes.stringType()),
//		  	Columns.column("User Password", "pass", DataTypes.stringType())
//		  	)
//		  .title(//title of the report
//		  	Components.text("RegistrationDetailsReport")
//		  		.setHorizontalAlignment(HorizontalAlignment.CENTER))
//		  .pageFooter(Components.pageXofY())//show page number on the page footer
//		  .setDataSource("select reg_id, name,fname,address,phone,mail,uname,pass from registation", connection);
//
//		try {
//			report.show();//show the report
//			//report.toPdf(new FileOutputStream("/Users/mkyong/Documents/workspace/report.pdf"));//export the report to a pdf file
//                        report.toPdf(new FileOutputStream("C:/Users/usr/Desktop/DEDAR/report.pdf"));
//                        JOptionPane.showMessageDialog(rootPane, "Report Created Successfully Just Check The File Directory..!");
//                        System.out.println("Report Created");
//                } 
//                catch (DRException e) {
//			e.printStackTrace();
//                        JOptionPane.showMessageDialog(rootPane, "Error,Report Not Created..!");
//                        System.out.println("Error Report");
//		} 
//                catch (FileNotFoundException e) {
//			e.printStackTrace();
//                        JOptionPane.showMessageDialog(rootPane, "Error,Report Not Created..!");
//                        System.out.println("Error Report");
//		}
		} 
//                catch (Exception e) {
//			e.printStackTrace();
//                        JOptionPane.showMessageDialog(rootPane, "Error,DataBase Not Connected..SQL Exceptions herer..!");
//                        System.out.println("Error SQL");
//			return;
//		}
        catch (Exception e) {
            e.printStackTrace();
        }finally {
            try {
                statement.close();
                connection.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }	
    }//GEN-LAST:event_printUserRegBtnActionPerformed

    private void prntDynBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prntDynBtnActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        Statement statement = null;
        try{
            connection = Database.getConnection();
            statement = connection.createStatement();
            //ReportBuilder rb=new ReportBuilder();
            JasperDesign jasDes= new JasperDesign();
            jasDes.setName("myreport");
            jasDes.setPageWidth(595);
            jasDes.setPageHeight(842);
            jasDes.setLeftMargin(20);
            jasDes.setRightMargin(20);
            jasDes.setTopMargin(20);
            jasDes.setBottomMargin(20);
            jasDes.setColumnWidth(555);
            
            // Style
            JRDesignStyle mystyle = new JRDesignStyle();
            mystyle.setName("mystyle");
            mystyle.setDefault(true);
            //mystyle.setFontName("DejaVu Sans");
            mystyle.setFontSize(11f);
            mystyle.setPdfFontName("Helvetica");
            mystyle.setPdfEncoding("UTF-8");
            jasDes.addStyle(mystyle);
            
            // Fields
                JRDesignField field1 = new JRDesignField();
                field1.setName("reg_id");
                field1.setValueClass(Integer.class);
                jasDes.addField(field1);

                JRDesignField field2 = new JRDesignField();
                field2.setName("name");
                field2.setValueClass(String.class);
                jasDes.addField(field2);

                JRDesignField field3 = new JRDesignField();
                field3.setName("fname");
                field3.setValueClass(String.class);
                jasDes.addField(field3);
                
                JRDesignField field4 = new JRDesignField();
                field4.setName("address");
                field4.setValueClass(String.class);
                jasDes.addField(field4);

                JRDesignField field5 = new JRDesignField();
                field5.setName("phone");
                field5.setValueClass(String.class);
                jasDes.addField(field5);
                
                JRDesignField field6 = new JRDesignField();
                field6.setName("mail");
                field6.setValueClass(String.class);
                jasDes.addField(field6);

                JRDesignField field7 = new JRDesignField();
                field7.setName("uname");
                field7.setValueClass(String.class);
                jasDes.addField(field7);
                
                JRDesignField field8 = new JRDesignField();
                field8.setName("pass");
                field8.setValueClass(String.class);
                jasDes.addField(field8);

                // Parameter
                JRDesignParameter jdp=new JRDesignParameter();
        JRDesignParameter par = new JRDesignParameter();
        par.setName("reg_id");
        par.setValueClass(Integer.class);
        jasDes.addParameter(par);

        // Query
        JRDesignQuery query = new JRDesignQuery();
        query.setText("SELECT * FROM registation WHERE reg_id = $P{reg_id}");
        jasDes.setQuery(query);

        // Title
        JRDesignBand titleBand = new JRDesignBand();
        titleBand.setHeight(50);

        JRDesignStaticText titleText = new JRDesignStaticText();
        titleText.setText("Inventory Users");
        titleText.setX(0);
        titleText.setY(10);
        titleText.setWidth(515);
        titleText.setHeight(30);
        //titleText.setHorizontalTextAlign(HorizontalTextAlignEnum.CENTER);
        titleText.setFontSize((int) 22f);
        titleBand.addElement(titleText);
        jasDes.setTitle(titleBand);
        System.out.println(titleText);
        // Detail
        JRDesignBand detailBand = new JRDesignBand();
        detailBand.setHeight(60);

        JRDesignTextField tf1 = new JRDesignTextField();
        tf1.setBlankWhenNull(true);
        tf1.setX(0);
        tf1.setY(10);
        tf1.setWidth(30);
        tf1.setHeight(30);
        tf1.setStyle(mystyle);
       // JRDesignExpression jd=;
        tf1.setExpression(new JRDesignExpression("$F{reg_id}"));
        System.out.println(tf1);
        detailBand.addElement(tf1);

        JRDesignTextField tf2 = new JRDesignTextField();
        tf2.setBlankWhenNull(true);
        tf2.setX(80);
        tf2.setY(10);
        tf2.setWidth(30);
        tf2.setHeight(30);
        tf2.setHorizontalTextAlign(HorizontalTextAlignEnum.LEFT);
        tf2.setStyle(mystyle);
        tf2.setExpression(new JRDesignExpression("$F{uname}"));
        detailBand.addElement(tf2);

        JRDesignTextField tf3 = new JRDesignTextField();
        tf3.setBlankWhenNull(true);
        tf3.setX(200);
        tf3.setY(10);
        tf3.setWidth(30);
        tf3.setHeight(30);
        tf3.setHorizontalTextAlign(HorizontalTextAlignEnum.RIGHT);
        tf3.setStyle(mystyle);
        tf3.setExpression(new JRDesignExpression("$F{fname}"));
        detailBand.addElement(tf3);
        
        JRDesignTextField tf4 = new JRDesignTextField();
        tf4.setBlankWhenNull(true);
        tf4.setX(200);
        tf4.setY(10);
        tf4.setWidth(30);
        tf4.setHeight(30);
        tf4.setHorizontalTextAlign(HorizontalTextAlignEnum.RIGHT);
        tf4.setStyle(mystyle);
        tf4.setExpression(new JRDesignExpression("$F{address}"));
        detailBand.addElement(tf4);
        
        JRDesignTextField tf5 = new JRDesignTextField();
        tf5.setBlankWhenNull(true);
        tf5.setX(200);
        tf5.setY(10);
        tf5.setWidth(30);
        tf5.setHeight(30);
        tf5.setHorizontalTextAlign(HorizontalTextAlignEnum.RIGHT);
        tf5.setStyle(mystyle);
        tf5.setExpression(new JRDesignExpression("$F{phone}"));
        detailBand.addElement(tf5);
        
        JRDesignTextField tf6 = new JRDesignTextField();
        tf6.setBlankWhenNull(true);
        tf6.setX(200);
        tf6.setY(10);
        tf6.setWidth(30);
        tf6.setHeight(30);
        tf6.setHorizontalTextAlign(HorizontalTextAlignEnum.RIGHT);
        tf6.setStyle(mystyle);
        tf6.setExpression(new JRDesignExpression("$F{mail}"));
        detailBand.addElement(tf6);
        
        JRDesignTextField tf7 = new JRDesignTextField();
        tf7.setBlankWhenNull(true);
        tf7.setX(200);
        tf7.setY(10);
        tf7.setWidth(30);
        tf7.setHeight(30);
        tf7.setHorizontalTextAlign(HorizontalTextAlignEnum.RIGHT);
        tf7.setStyle(mystyle);
        tf7.setExpression(new JRDesignExpression("$F{uname}"));
        detailBand.addElement(tf7);
        
        JRDesignTextField tf8 = new JRDesignTextField();
        tf8.setBlankWhenNull(true);
        tf8.setX(200);
        tf8.setY(10);
        tf8.setWidth(30);
        tf8.setHeight(30);
        tf8.setHorizontalTextAlign(HorizontalTextAlignEnum.RIGHT);
        tf8.setStyle(mystyle);
        tf8.setExpression(new JRDesignExpression("$F{pass}"));
        detailBand.addElement(tf8);
        
        
        ((JRDesignSection) jasDes.getDetailSection()).addBand(detailBand);

        //return jasDes;
            //JasperDesign jdes =(JasperDesign) new ReportBuilder().build();
            JasperReport report = JasperCompileManager.compileReport(jasDes);

            HashMap params = new HashMap();
            params.put("reg_id", 1);
            //params.put("rtitle", "Report Title Here");
            System.out.println(params);
            JasperPrint jprint = JasperFillManager.fillReport(report, params, connection);
            System.out.println(jprint);
            JasperExportManager.exportReportToPdfFile(jprint,
                    "src/management/system/Resources/UserReport.pdf");
            System.out.println("please give right dir");
                    //C:\Users\User\Documents\NetBeansProjects\management system\src\management\system\Resources
        }catch (SQLException e){
		e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "DataBase Not Connected..!");
                System.out.println("Report Created");
		//return;
	} catch (JRException ex) {
        Logger.getLogger(EditRegUser.class.getName()).log(Level.SEVERE, null, ex);
    }
//        JasperReportBuilder rt1=DynamicReports.report();
//        //JasperReportBuilder report = DynamicReports.report();
//            rt1
//            .columns(
//	      Columns.column("Registration Id", "id", DataTypes.integerType()),
//	      Columns.column("Name", "name", DataTypes.stringType()),
//	      Columns.column("Fathers Name", "fname", DataTypes.stringType()),
//              Columns.column("User Address", "address", DataTypes.integerType()),
//	      Columns.column("Phone", "phone", DataTypes.stringType()),
//	      Columns.column("Email", "mail", DataTypes.stringType()),
//              Columns.column("User Name", "uname", DataTypes.integerType()),
//	      Columns.column("Password", "pass", DataTypes.stringType())
//	      //Columns.column("Date", "date", DataTypes.dateType())
//            )
//	  .title(//title of the report
//	      Components.text("User Registration Dynamic Report")
//                .setHorizontalAlignment(HorizontalAlignment.CENTER))
//		  .pageFooter(Components.pageXofY())//show page number on the page footer
//		  .setDataSource("select reg_id,name,fname, "
//                          + "address, phone, mail,"
//                          + " uname, pass from registation", connection);
//            try {
//                //show the report
//		rt1.show();
//                System.out.println("Report Created");
//                //export the report to a pdf file
//		rt1.toPdf(new FileOutputStream("c:/Desktop/report.pdf"));
//                } catch (FileNotFoundException e) {
//                        e.printStackTrace();
//                        System.out.println("Error File Not Found..");
//                } catch (DRException ex) {
//        Logger.getLogger(EditRegUser.class.getName()).log(Level.SEVERE, null, ex);
//    }
            JOptionPane.showMessageDialog(rootPane, "DataBase Connected..!");
            System.out.println("Report Created");
        
//        finally {
//                try {
//                    statement.close();
//                    connection.close();
//                    JOptionPane.showMessageDialog(rootPane, "DataBase Connection Closed..!");
//                    System.out.println("Report Created and connection closed");
//                }catch (Exception e){
//                e.printStackTrace();
//                JOptionPane.showMessageDialog(rootPane, "Finally Error..!");
//                System.out.println("Finally Error");
//            }
//        }      
    }//GEN-LAST:event_prntDynBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRegUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRegUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRegUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRegUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRegUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton backToSignupBtn;
    private javax.swing.JButton clearRegBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField email;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField phone;
    private javax.swing.JButton printUserRegBtn;
    private javax.swing.JButton prntDynBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField userId;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        userId.setText("");
        name.setText("");
        fName.setText("");
        address.setText("");
        phone.setText("");
        email.setText("");
        userName.setText("");
        pass.setText("");
    }

//    private void createReportToPrint() {
//        
//    }
}
