/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management.system;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import static java.sql.Date.valueOf;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.text.BadLocationException;
import static management.system.ManagementSys.logger;

/**
 *
 * @Md.Dedarul Hasan
 */
public class EditPurchaseInfo extends javax.swing.JFrame {
//private JPanel contentpane;
//private JLabel lbl;
static final Logger logger = Logger.getLogger(EditPurchaseInfo.class.getName());
    /**
     * Creates new form SearchPurchaseInfo
     */
    Connection con;
    Statement s;
    ResultSet rs;
    PreparedStatement ps;
    
    public EditPurchaseInfo() {
        con=Database.getConnection();
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        purchaseId = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        pPrice = new javax.swing.JTextField();
        tPrice = new javax.swing.JTextField();
        pDate = new com.toedter.calendar.JDateChooser();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        clearPurchaseBtn = new javax.swing.JButton();
        backToPurchaseBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        productId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(485, 185));

        jLabel1.setText("Purchase ID:");

        jLabel2.setText("Product Name:");

        jLabel3.setText("Quantity:");

        jLabel4.setText("P.Price Unit:");

        jLabel5.setText("Total Price:");

        jLabel6.setText("Purchase Date :");

        purchaseId.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                purchaseIdPropertyChange(evt);
            }
        });
        purchaseId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchaseIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                purchaseIdKeyTyped(evt);
            }
        });

        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Please Enter Purchase  ID First To Search & Update Purchase  Informations Here");

        clearPurchaseBtn.setText("Clear");
        clearPurchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPurchaseBtnActionPerformed(evt);
            }
        });

        backToPurchaseBtn.setText("Back To Purchase");
        backToPurchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToPurchaseBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Product ID");

        productId.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                productIdComponentAdded(evt);
            }
        });
        productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdActionPerformed(evt);
            }
        });
        productId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productIdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(updateBtn)
                                .addGap(32, 32, 32)
                                .addComponent(deleteBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(pDate, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(clearPurchaseBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitBtn)
                                .addGap(70, 70, 70))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backToPurchaseBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(quantity, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(productName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(purchaseId)
                                            .addComponent(productId, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(pPrice))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(purchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel2)
                        .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(deleteBtn)
                    .addComponent(updateBtn)
                    .addComponent(clearPurchaseBtn)
                    .addComponent(backToPurchaseBtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearPurchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPurchaseBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearPurchaseBtnActionPerformed

    private void backToPurchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToPurchaseBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Want to back Order Informations, Thanks..!!");
        ManagementSys mSys=new ManagementSys();
        mSys.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        mSys.setVisible(true);
        dispose();
    }//GEN-LAST:event_backToPurchaseBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
//        String purId = purchaseId.getText();
//            String productid=productId.getText();                
//                String productname=productName.getText();
//                    String qty=quantity.getText();
//                        String purchasePrice=pPrice.getText();
//                            String totalprice=tPrice.getText();
//                                java.sql.Date date = new java.sql.Date(pDate.getDate().getTime());
//        if(purId.equals("")){
//            JOptionPane.showMessageDialog(null, "Purchase Id is mandatory..!!");
//        }
//        if(productid.equals("")){
//            JOptionPane.showMessageDialog(null, "Product Id is mandatory..!!");
//        }
//        if(productname.equals("")){
//            JOptionPane.showMessageDialog(null, "Product Name is mandatory..!!");
//        }
//        if(qty.equals("")){
//            JOptionPane.showMessageDialog(null, "Quantity is mandatory..!!");
//        }
//        if(purchasePrice.equals("")){
//            JOptionPane.showMessageDialog(null, "Purchase price is mandatory..!!");
//        }
//        if(totalprice.equals("")){
//            JOptionPane.showMessageDialog(null, "Tot Price is mandatory..!!");
//        }
//        if(date.equals(null)){
//            JOptionPane.showMessageDialog(null, "Date is mandatory..!!");
//        }
        try {
            
            String sql="update purchase set product_id=?,quantity=?,pPrice=?,totalPrice=?,pDate=?,product_name=? where purchase_id=?";
            ps=con.prepareStatement(sql);
            //For product id parse into int
            String productID = productId.getText();
            int proID = Integer.parseInt(productID);
            if(proID==0){
                JOptionPane.showMessageDialog(null, "Error,!","collaborate ",0);
            }
            ps.setInt(1, proID);           
            ps.setString(2, quantity.getText());
            ps.setString(3, pPrice.getText());
            ps.setString(4, tPrice.getText());
            //For Date Format
            pDate.getDate().getTime();
            java.sql.Date date = new java.sql.Date(pDate.getDate().getTime());
            ps.setDate(5, date);
            ps.setString(6, productName.getText());
            ps.setString(7, purchaseId.getText());          
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Purchase Information Updated Successfully");
            System.out.println("Database Updated");
            //*******************************************************
                logger.log(Level.SEVERE, "Login Successfull");
                logger.info("This is info message");
                logger.config("inventory system");
                logger.warning("Login Button Fired");
                System.out.println("Logic executed successfully....");
                //*******************************************************
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error,Purchase Information Not Updated..!");
            System.out.println("Database not Updated");
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void purchaseIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchaseIdKeyReleased
        // TODO add your handling code here:
        try {
            String sql="select purchase_id,product_id,product_name,quantity,pPrice,totalPrice,pDate from purchase where purchase_id=?";
            ps=con.prepareStatement(sql);
            String purId = purchaseId.getText();
            int purchaseID = Integer.parseInt(purId);
            ps.setInt(1, purchaseID);
            rs=ps.executeQuery();
            if(rs.next()){

                String productid=rs.getString("product_id");
                productId.setText(productid);
                String productname=rs.getString("product_name");
                productName.setText(productname);
                String qty=rs.getString("quantity");
                quantity.setText(qty);
                String purchasePrice=rs.getString("pPrice");
                pPrice.setText(purchasePrice);
                String totalprice=rs.getString("totalPrice");
                tPrice.setText(totalprice);
                Timestamp timestamp = rs.getTimestamp("pDate");
                pDate.setDate(timestamp);
                              
            }
        } catch (Exception e) {
            System.out.println("ERROR..!");
            JOptionPane.showMessageDialog(rootPane, "Error Occured..!@");
        }
//        if(purchaseId.getText().isEmpty()|| productId.getText().isEmpty() || productName.getText().isEmpty() ||quantity.getText().isEmpty() || pPrice.getText().isEmpty() || tPrice.getText().isEmpty() || pDate.getCalendar().isLenient()){
//            lbl=new JLabel("");
//            lbl.setBounds(255, 65, 162, 22);
//            this.add(lbl);
//            
//            //JOptionPane.showMessageDialog(rootPane, "Please Enter All Field To Update..!");
//            lbl.setText("please fill all text fields");
//        }
    }//GEN-LAST:event_purchaseIdKeyReleased

    private void productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdActionPerformed

    private void purchaseIdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_purchaseIdPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseIdPropertyChange

    private void purchaseIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchaseIdKeyTyped
        // TODO add your handling code here:
        if(productId.getText().equals(" ")){
           JOptionPane.showMessageDialog(rootPane, "Error Occured..!@"); 
        }
//        int key=evt.getKeyChar();
//        if((key>=evt.VK_0&&key<=evt.VK_9)||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE){
//            purchaseId.setEditable(true);
//            purchaseId.setBackground(Color.GREEN);
//        }
//        else{
//            purchaseId.setEditable(false);
//            purchaseId.setBackground(Color.RED);
//        }
    }//GEN-LAST:event_purchaseIdKeyTyped

    private void productIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIdKeyTyped
        // TODO add your handling code here:
        
        
//        if(productId.getText().equals(" ")){
//           JOptionPane.showMessageDialog(rootPane, "Error Occured..!@"); 
//        }
//    try {
//        if(productId.getText()==null){
//            JOptionPane.showMessageDialog(rootPane, "Error Occured..!@"); 
//        } 
//        } catch (Exception ex) {
//            Logger.getLogger(EditPurchaseInfo.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_productIdKeyTyped

    private void productIdComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_productIdComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPurchaseInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToPurchaseBtn;
    private javax.swing.JButton clearPurchaseBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser pDate;
    private javax.swing.JTextField pPrice;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField purchaseId;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField tPrice;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        purchaseId.setText("");
        productId.setText("");
        productName.setText("");
        quantity.setText("");
        pPrice.setText("");
        tPrice.setText("");
        pDate.setCalendar(null);
    }
}
