/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static management.system.EditPurchaseInfo.logger;
import static management.system.ManagementSys.logger;

/**
 *
 * @Md.Dedarul Hasan
 */
public class EditOrderInfo extends javax.swing.JFrame {
static final Logger logger = Logger.getLogger(EditOrderInfo.class.getName());
    /**
     * Creates new form SearchOrderInfo
     */
    Connection con;
    Statement s;
    ResultSet rs;
    PreparedStatement ps;
    public EditOrderInfo() {
        initComponents();
        con=Database.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        orderId = new javax.swing.JTextField();
        customer = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        orderNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        product = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        sPrice = new javax.swing.JTextField();
        tprice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        oDate = new com.toedter.calendar.JDateChooser();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        clearOrderBtn = new javax.swing.JButton();
        backOrderBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        productId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        purchaseId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EditOrderInfo");
        setLocation(new java.awt.Point(485, 185));
        setPreferredSize(new java.awt.Dimension(900, 400));
        setSize(new java.awt.Dimension(1000, 300));

        jLabel1.setText("Order ID:");

        jLabel2.setText("Customer Name:");

        jLabel3.setText("Phone No.");

        jLabel4.setText("E-mail");

        jLabel5.setText("Order Number:");

        orderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orderIdKeyReleased(evt);
            }
        });

        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        jLabel6.setText("Date:");

        jLabel7.setText("Product Name:");

        jLabel8.setText("Quantity:");

        jLabel9.setText("Sell Price:");

        sPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("Total Price:");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Please Enter Order ID First To Search & Update Order Informations Here");

        clearOrderBtn.setText("Clear");
        clearOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOrderBtnActionPerformed(evt);
            }
        });

        backOrderBtn.setText("Back To Order");
        backOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backOrderBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Product Id:");

        jLabel13.setText("Purchase Id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(orderId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(updateBtn)
                                        .addGap(31, 31, 31)
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(oDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(orderNum, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                        .addGap(54, 54, 54)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel10)
                            .addComponent(backOrderBtn)
                            .addComponent(jLabel13))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantity)
                            .addComponent(sPrice)
                            .addComponent(tprice)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clearOrderBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(exitBtn)
                                .addGap(22, 22, 22))
                            .addComponent(productId)
                            .addComponent(purchaseId))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(purchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(orderNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(sPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(tprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(backOrderBtn)
                    .addComponent(clearOrderBtn)
                    .addComponent(exitBtn))
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
        String sql="update order_table set customer_name=?,phone_no=?,e_mail=?,ord_number=?,"
        + "ord_date=?,product_name=?,product_id=?,purchase_id=?,quantity=?,sell_price=?,total_price=?";
        try {
            ps=con.prepareStatement(sql);
//            String orderID = orderId.getText();
//            int ordID = Integer.parseInt(orderID);
//            ps.setInt(1, ordID);           
            ps.setString(1, customer.getText());
            ps.setString(2, phone.getText());
            ps.setString(3, email.getText());
            ps.setString(4, orderNum.getText());
            
            oDate.getDate().getTime();
            java.sql.Date date = new java.sql.Date(oDate.getDate().getTime());
            ps.setDate(5, date);
            
            ps.setString(6, product.getText());
            
            String proId = productId.getText();
            int proID = Integer.parseInt(proId);
            ps.setInt(7, proID);
            
            String purId = purchaseId.getText();
            int purID = Integer.parseInt(purId);
            ps.setInt(8, purID);
            
            String qnty = quantity.getText();
            int quantityQ = Integer.parseInt(qnty);
            ps.setInt(9, quantityQ);
            
            String salePrice = sPrice.getText();
            int sPrice = Integer.parseInt(salePrice);
            ps.setInt(10, sPrice);
            
            String totPrice = tprice.getText();
            int totalPrice = Integer.parseInt(totPrice);
            ps.setInt(11, totalPrice);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Order Information Updated Successfully");
            System.out.println("Database Updated");
            //*******************************************************
                logger.log(Level.SEVERE, "Order Update Successfull");
                logger.info("This Is Order Update info message");
                logger.config("Inventory System");
                logger.warning("Order Update Button Fired");
                System.out.println("Order Update executed successfully....");
        } catch (SQLException ex) {
            Logger.getLogger(EditOrderInfo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "SQL Exception Occured....");
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();   
    }//GEN-LAST:event_exitBtnActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void clearOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOrderBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearOrderBtnActionPerformed

    private void backOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backOrderBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Want to back Order Informations, Thanks..!!");
        ManagementSys mSys=new ManagementSys();
        mSys.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        mSys.setVisible(true);
        dispose();
    }//GEN-LAST:event_backOrderBtnActionPerformed

    private void orderIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderIdKeyReleased
        // TODO add your handling code here:
        try {
            String sql="select order_id,customer_name,phone_no,e_mail,ord_number,ord_date,product_name,product_id, purchase_id,quantity,sell_price,total_price from order_table where order_id=?";
            System.out.println("Search Query Executed Successfully....");
            ps=con.prepareStatement(sql);
            String orderID = orderId.getText();
            int ordID = Integer.parseInt(orderID);
            ps.setInt(1, ordID);
            rs=ps.executeQuery();
            if(rs.next()){

                String customername=rs.getString("customer_name");
                customer.setText(customername);
                String phoneno=rs.getString("phone_no");
                phone.setText(phoneno);
                String mail=rs.getString("e_mail");
                email.setText(mail);
                String ordNum=rs.getString("ord_number");
                orderNum.setText(ordNum);
//                pDate.getDate().getTime();
//                java.sql.Date date = new java.sql.Date(pDate.getDate().getTime());
                Timestamp timestamp = rs.getTimestamp("ord_date");
                oDate.setDate(timestamp);
                String productname=rs.getString("product_name");
                product.setText(productname);
                
                String proId=rs.getString("product_id");
                productId.setText(proId);
                String purID=rs.getString("purchase_id");
                purchaseId.setText(purID);
                String qnt=rs.getString("quantity");
                quantity.setText(qnt);
                String sellPrice=rs.getString("sell_price");
                sPrice.setText(sellPrice);
                String totalPrice=rs.getString("total_price");
                tprice.setText(totalPrice);
                //*******************************************************
                logger.log(Level.SEVERE, "Search Order Successfull");
                logger.info("This Is Order Search info message");
                logger.config("Inventory System Order");
                logger.warning("Order Serch Key Fired");
                System.out.println("Order Search executed successfully....");
                JOptionPane.showMessageDialog(rootPane, "Order Information Loaded Successfully");
                //*******************************************************                                          
            }
        } catch (Exception e) {
            System.out.println("ERROR..!");
            JOptionPane.showMessageDialog(rootPane, "Error Occured..!@");
        }
    }//GEN-LAST:event_orderIdKeyReleased

    private void sPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditOrderInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backOrderBtn;
    private javax.swing.JButton clearOrderBtn;
    private javax.swing.JTextField customer;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField email;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser oDate;
    private javax.swing.JTextField orderId;
    private javax.swing.JTextField orderNum;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField product;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField purchaseId;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField sPrice;
    private javax.swing.JTextField tprice;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        orderId.setText("");
        customer.setText("");
        phone.setText("");
        email.setText("");
        orderNum.setText("");
        oDate.setCalendar(null);
        product.setText("");
        quantity.setText("");
        sPrice.setText("");
        tprice.setText("");
    }
}
