/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management.system;

import java.awt.BorderLayout;
import java.util.prefs.Preferences;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import management.system.MyFrames.EditPurchaseInformation;
import management.system.showTableLog.ShowOrdersLog;
import management.system.showTableLog.ShowPurchasedLog;
import management.system.showTableLog.ShowRegistrationLog;


/**
 *
 * @author User
 */
public class InventoryManagementSystem extends javax.swing.JFrame {

    /**
     * Creates new form InventoryManagementSystem
     */
    public InventoryManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showDesktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        logoutBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        homeMenu1 = new javax.swing.JMenu();
        homeMenu2 = new javax.swing.JMenu();
        homeMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        purchaseMenu1 = new javax.swing.JMenu();
        purchaseMenu2 = new javax.swing.JMenu();
        purchaseMenu3 = new javax.swing.JMenu();
        purchaseMenu4 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuOrder1 = new javax.swing.JMenu();
        menuOrder2 = new javax.swing.JMenu();
        menuOrder3 = new javax.swing.JMenu();
        menuOrder4 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        userMenu1 = new javax.swing.JMenu();
        userMenu2 = new javax.swing.JMenu();
        userMenu3 = new javax.swing.JMenu();
        userMenu4 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        logMenu1 = new javax.swing.JMenu();
        logMenu2 = new javax.swing.JMenu();
        logMenu3 = new javax.swing.JMenu();
        othersMenu = new javax.swing.JMenu();
        calculatorMenu = new javax.swing.JMenu();
        emailMenu = new javax.swing.JMenu();
        chatClientMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVENTORY MANAGEMENT SYSTEM");
        setLocation(new java.awt.Point(110, 50));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        logoutBTN.setText("Logout");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBTN)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBTN)
                .addGap(25, 25, 25))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/web folder.png"))); // NOI18N

        showDesktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        showDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout showDesktopLayout = new javax.swing.GroupLayout(showDesktop);
        showDesktop.setLayout(showDesktopLayout);
        showDesktopLayout.setHorizontalGroup(
            showDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showDesktopLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 546, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        showDesktopLayout.setVerticalGroup(
            showDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(showDesktop);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 0));
        jMenuBar1.setForeground(new java.awt.Color(153, 255, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(150, 100));

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu1.setForeground(new java.awt.Color(51, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/home.png"))); // NOI18N
        jMenu1.setText("HOME");
        jMenu1.setInheritsPopupMenu(true);
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 100));
        jMenu1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/arrow.png"))); // NOI18N

        homeMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/interact.png"))); // NOI18N
        homeMenu1.setText("Log In");
        homeMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenu1MenuSelected(evt);
            }
        });
        homeMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenu1MouseClicked(evt);
            }
        });
        jMenu1.add(homeMenu1);

        homeMenu2.setText("Sign Up");
        homeMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenu2MouseClicked(evt);
            }
        });
        jMenu1.add(homeMenu2);

        homeMenu3.setText("Log Out");
        homeMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(homeMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(51, 255, 204));
        jMenu2.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu2.setForeground(new java.awt.Color(51, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/vault.png"))); // NOI18N
        jMenu2.setText("PURCHASE");
        jMenu2.setAlignmentX(1.0F);
        jMenu2.setBorderPainted(true);
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 100));

        purchaseMenu1.setText("Purchase Product");
        purchaseMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                purchaseMenu1MenuSelected(evt);
            }
        });
        purchaseMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseMenu1MouseClicked(evt);
            }
        });
        purchaseMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                purchaseMenu1KeyPressed(evt);
            }
        });
        jMenu2.add(purchaseMenu1);

        purchaseMenu2.setText("Update Product");
        purchaseMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseMenu2MouseClicked(evt);
            }
        });
        jMenu2.add(purchaseMenu2);

        purchaseMenu3.setText("Delete Product");
        purchaseMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseMenu3MouseClicked(evt);
            }
        });
        jMenu2.add(purchaseMenu3);

        purchaseMenu4.setText("Search & Report");
        purchaseMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseMenu4MouseClicked(evt);
            }
        });
        jMenu2.add(purchaseMenu4);

        jMenuBar1.add(jMenu2);

        jMenu9.setBackground(new java.awt.Color(255, 204, 255));
        jMenu9.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu9.setForeground(new java.awt.Color(51, 0, 0));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/pathing.png"))); // NOI18N
        jMenu9.setText("ORDER DETAILS");
        jMenu9.setOpaque(true);
        jMenu9.setPreferredSize(new java.awt.Dimension(150, 100));

        menuOrder1.setText("Order Product");
        menuOrder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOrder1MouseClicked(evt);
            }
        });
        jMenu9.add(menuOrder1);

        menuOrder2.setText("Update Order");
        menuOrder2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOrder2MouseClicked(evt);
            }
        });
        jMenu9.add(menuOrder2);

        menuOrder3.setText("Delete Order");
        menuOrder3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOrder3MouseClicked(evt);
            }
        });
        jMenu9.add(menuOrder3);

        menuOrder4.setText("Search & Report");
        menuOrder4.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuOrder4MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu9.add(menuOrder4);

        jMenuBar1.add(jMenu9);

        jMenu13.setBackground(new java.awt.Color(255, 255, 204));
        jMenu13.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu13.setForeground(new java.awt.Color(51, 0, 0));
        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/people.png"))); // NOI18N
        jMenu13.setText("USER");
        jMenu13.setOpaque(true);
        jMenu13.setPreferredSize(new java.awt.Dimension(150, 100));

        userMenu1.setText("Create User");
        userMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMenu1MouseClicked(evt);
            }
        });
        jMenu13.add(userMenu1);

        userMenu2.setText("Update User");
        userMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMenu2MouseClicked(evt);
            }
        });
        jMenu13.add(userMenu2);

        userMenu3.setText("Delete User");
        userMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMenu3MouseClicked(evt);
            }
        });
        jMenu13.add(userMenu3);

        userMenu4.setText("Search & Report");
        userMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMenu4MouseClicked(evt);
            }
        });
        jMenu13.add(userMenu4);

        jMenuBar1.add(jMenu13);

        jMenu14.setBackground(new java.awt.Color(204, 255, 204));
        jMenu14.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu14.setForeground(new java.awt.Color(51, 0, 0));
        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/plus.png"))); // NOI18N
        jMenu14.setText("REPORTS LOGS");
        jMenu14.setOpaque(true);
        jMenu14.setPreferredSize(new java.awt.Dimension(150, 100));

        logMenu1.setText("User Logs");
        logMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMenu1MouseClicked(evt);
            }
        });
        jMenu14.add(logMenu1);

        logMenu2.setText("Purchase Logs");
        logMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMenu2MouseClicked(evt);
            }
        });
        jMenu14.add(logMenu2);

        logMenu3.setText("Order Logs");
        logMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMenu3MouseClicked(evt);
            }
        });
        jMenu14.add(logMenu3);

        jMenuBar1.add(jMenu14);

        othersMenu.setBackground(new java.awt.Color(153, 153, 0));
        othersMenu.setBorder(new javax.swing.border.MatteBorder(null));
        othersMenu.setForeground(new java.awt.Color(51, 0, 0));
        othersMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/system/PNG/world.png"))); // NOI18N
        othersMenu.setText("OTHERS");
        othersMenu.setBorderPainted(true);
        othersMenu.setOpaque(true);
        othersMenu.setPreferredSize(new java.awt.Dimension(150, 100));
        othersMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                othersMenuMenuSelected(evt);
            }
        });
        othersMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                othersMenuMouseClicked(evt);
            }
        });

        calculatorMenu.setText("Calculator");
        othersMenu.add(calculatorMenu);

        emailMenu.setText("Email");
        othersMenu.add(emailMenu);

        chatClientMenu.setText("Chat Client");
        othersMenu.add(chatClientMenu);

        jMenuBar1.add(othersMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void othersMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_othersMenuMenuSelected
        // TODO add your handling code here:
        
//        calculator.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        calculator.setVisible(true);
//        dispose();
    }//GEN-LAST:event_othersMenuMenuSelected

    private void homeMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenu1MenuSelected
        // TODO add your handling code here:
//        LoginSystem lsm=new LoginSystem();
//        lsm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        lsm.setVisible(true);
    }//GEN-LAST:event_homeMenu1MenuSelected

    private void purchaseMenu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchaseMenu1KeyPressed
        // TODO add your handling code here:
       EditPurchaseInformation ePurchase=new EditPurchaseInformation();
       this.add(ePurchase);
       ePurchase.setVisible(true);  
    }//GEN-LAST:event_purchaseMenu1KeyPressed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Want to Logout from the system..!");
        LoginSystem lstm=new LoginSystem();
        lstm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lstm.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void purchaseMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_purchaseMenu1MenuSelected
        // TODO add your handling code here:
//        EditPurchaseInformation ePurchase=new EditPurchaseInformation();
//        this.showDesktop.add(ePurchase);
//        ePurchase.setSize(300,300);
//        ePurchase.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        ePurchase.setVisible(true);  
//       EditPurchaseInfo ePurchase=new EditPurchaseInfo();
//       ePurchase.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//       ePurchase.setSize(750,400);
//       ePurchase.setLocation(600, 200);
//       ePurchase.setVisible(true);  

        
        //ePurchase.setSize(650,650);
        //ePurchase.setVisible(true);
       
    }//GEN-LAST:event_purchaseMenu1MenuSelected

    private void purchaseMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseMenu1MouseClicked
        // TODO add your handling code here:
        
//        EditPurchaseInfo purchaseProduct=new EditPurchaseInfo();
//        showDesktop.add(purchaseProduct);
//        showDesktop.setVisible(true);
//        //this.showDesktop.add(purchaseProduct);        
//        purchaseProduct.setVisible(true);
       //this.jInternalFrame1.add(ePurchase);
       //Preferences p = setVisible(true);
       //this.add(ePurchase).setVisible(true);***
       
       EditPurchaseInfo ePurchase=new EditPurchaseInfo();
       ePurchase.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       ePurchase.setSize(700,400);
       ePurchase.setVisible(true); 

//                JFrame application = new JFrame();
//		application.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//		application.add(ePurchase);
//		application.setSize(650,850);
//		application.setVisible(true);

        //ePurchase.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //ePurchase.setSize(650,650);
       // ePurchase.setVisible(true);
    }//GEN-LAST:event_purchaseMenu1MouseClicked

    private void menuOrder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrder1MouseClicked
        // TODO add your handling code here:
       EditOrderInfo eOrder=new EditOrderInfo();
       eOrder.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eOrder.setSize(700,400);
       eOrder.setVisible(true); 
    }//GEN-LAST:event_menuOrder1MouseClicked

    private void userMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenu1MouseClicked
        // TODO add your handling code here:
       EditRegUser eUser=new EditRegUser();
       eUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eUser.setSize(700,400);
       eUser.setVisible(true); 
    }//GEN-LAST:event_userMenu1MouseClicked

    private void homeMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenu3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Want to Logout from the system..!");
        LoginSystem lstm=new LoginSystem();
        lstm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lstm.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMenu3MouseClicked

    private void homeMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenu2MouseClicked
        // TODO add your handling code here:
       EditRegUser eUser=new EditRegUser();
       eUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eUser.setSize(700,400);
       eUser.setVisible(true); 
    }//GEN-LAST:event_homeMenu2MouseClicked

    private void menuOrder4MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuOrder4MenuKeyPressed
        // TODO add your handling code here:
       EditOrderInfo eOrder=new EditOrderInfo();
       eOrder.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eOrder.setSize(700,400);
       eOrder.setVisible(true);
    }//GEN-LAST:event_menuOrder4MenuKeyPressed

    private void menuOrder3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrder3MouseClicked
        // TODO add your handling code here:
       EditOrderInfo eOrder=new EditOrderInfo();
       eOrder.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eOrder.setSize(700,400);
       eOrder.setVisible(true);
    }//GEN-LAST:event_menuOrder3MouseClicked

    private void menuOrder2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrder2MouseClicked
        // TODO add your handling code here:
       EditOrderInfo eOrder=new EditOrderInfo();
       eOrder.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eOrder.setSize(700,400);
       eOrder.setVisible(true);
    }//GEN-LAST:event_menuOrder2MouseClicked

    private void purchaseMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseMenu2MouseClicked
        // TODO add your handling code here:
       EditPurchaseInfo ePurchase=new EditPurchaseInfo();
       ePurchase.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       ePurchase.setSize(700,400);
       ePurchase.setVisible(true); 
    }//GEN-LAST:event_purchaseMenu2MouseClicked

    private void purchaseMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseMenu3MouseClicked
        // TODO add your handling code here:
       EditPurchaseInfo ePurchase=new EditPurchaseInfo();
       ePurchase.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       ePurchase.setSize(700,400);
       ePurchase.setVisible(true); 
    }//GEN-LAST:event_purchaseMenu3MouseClicked

    private void purchaseMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseMenu4MouseClicked
        // TODO add your handling code here:
       EditPurchaseInfo ePurchase=new EditPurchaseInfo();
       ePurchase.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       ePurchase.setSize(700,400);
       ePurchase.setVisible(true); 
    }//GEN-LAST:event_purchaseMenu4MouseClicked

    private void userMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenu2MouseClicked
        // TODO add your handling code here:
       EditRegUser eUser=new EditRegUser();
       eUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eUser.setSize(700,400);
       eUser.setVisible(true); 
    }//GEN-LAST:event_userMenu2MouseClicked

    private void userMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenu3MouseClicked
        // TODO add your handling code here:
       EditRegUser eUser=new EditRegUser();
       eUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eUser.setSize(700,400);
       eUser.setVisible(true); 
    }//GEN-LAST:event_userMenu3MouseClicked

    private void userMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenu4MouseClicked
        // TODO add your handling code here:
       EditRegUser eUser=new EditRegUser();
       eUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       eUser.setSize(700,400);
       eUser.setVisible(true); 
    }//GEN-LAST:event_userMenu4MouseClicked

    private void homeMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenu1MouseClicked
        // TODO add your handling code here:
        LoginSystem lsm=new LoginSystem();
        lsm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lsm.setVisible(true);
    }//GEN-LAST:event_homeMenu1MouseClicked

    private void othersMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othersMenuMouseClicked
        // TODO add your handling code here:
        MainCalculator cal=new MainCalculator();
        cal.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //cal.setDefaultCloseOperation(ICONIFIED);
        cal.setVisible(true);
    }//GEN-LAST:event_othersMenuMouseClicked

    private void logMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMenu1MouseClicked
        // TODO add your handling code here:
       ShowRegistrationLog regShow=new ShowRegistrationLog();
       //this.add(regShow);
       regShow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       regShow.setSize(700,400);
       regShow.setVisible(true); 
    }//GEN-LAST:event_logMenu1MouseClicked

    private void logMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMenu2MouseClicked
        // TODO add your handling code here:
       ShowPurchasedLog purchaseShow=new ShowPurchasedLog();;
       //this.add(purchaseShow);
       purchaseShow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       purchaseShow.setSize(700,400);
       purchaseShow.setVisible(true); 
    }//GEN-LAST:event_logMenu2MouseClicked

    private void logMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMenu3MouseClicked
        // TODO add your handling code here:
       ShowOrdersLog ordlog=new ShowOrdersLog();
       //this.add(ordlog);
       ordlog.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       ordlog.setSize(700,400);
       ordlog.setVisible(true); 
    }//GEN-LAST:event_logMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu calculatorMenu;
    private javax.swing.JMenu chatClientMenu;
    private javax.swing.JMenu emailMenu;
    private javax.swing.JMenu homeMenu1;
    private javax.swing.JMenu homeMenu2;
    private javax.swing.JMenu homeMenu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu logMenu1;
    private javax.swing.JMenu logMenu2;
    private javax.swing.JMenu logMenu3;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JMenu menuOrder1;
    private javax.swing.JMenu menuOrder2;
    private javax.swing.JMenu menuOrder3;
    private javax.swing.JMenu menuOrder4;
    private javax.swing.JMenu othersMenu;
    private javax.swing.JMenu purchaseMenu1;
    private javax.swing.JMenu purchaseMenu2;
    private javax.swing.JMenu purchaseMenu3;
    private javax.swing.JMenu purchaseMenu4;
    private javax.swing.JDesktopPane showDesktop;
    private javax.swing.JMenu userMenu1;
    private javax.swing.JMenu userMenu2;
    private javax.swing.JMenu userMenu3;
    private javax.swing.JMenu userMenu4;
    // End of variables declaration//GEN-END:variables
}
